message:
  default:
    welcome: Welcome common...
    goodbye: Goodbye common...
JAVA_HOME: This value is javahome

---

spring:
  profiles: local

---
spring:
  profiles: dev

message:
  default:
    welcome: Welcome dev...
    goodbye: Goodbye dev...

---
spring:
  profiles: qa

message:
  default:
    welcome: Welcome qa...
    goodbye: Goodbye qa...