
## configure common properties here

JAVA_HOME: This value is javahome
message:
  default:
    welcome: Welcome local...
    goodbye: Goodbye local...

---
## configure local properties here

spring:
  profiles: local
server:
  port: 8061

---
## configure dev properties here

spring:
  profiles: dev

message:
  default:
    welcome: Welcome dev...
    goodbye: Goodbye dev...
server:
  port: 8051

---
## configure qa properties here

spring:
  profiles: qa

message:
  default:
    welcome: Welcome qa...
    goodbye: Goodbye qa...
server:
  port: 8041